DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user(
 	`uno` INT(4) NOT NULL AUTO_INCREMENT COMMENT '用户ID',   
 	`email` VARCHAR(100) NOT NULL DEFAULT '匿名' COMMENT '姓名',
 	`telephone` VARCHAR(20) NOT NULL DEFAULT '010-12345678' COMMENT '密码',
 	`password` VARCHAR(100) NOT NULL DEFAULT '123456' COMMENT '密码',
 	PRIMARY KEY(`uno`)  
)ENGINE=INNODB DEFAULT CHARSET=utf8;